on:
  push:
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "**/yarn.lock"
      - "public/**"
      - ".github/workflows/ci.yml"
      - "db/data.json"

jobs:
  jsize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - uses: actions/cache@v1
        with:
          path: db/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('db/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install dependencies
        run: |
          cd db
          command -v bundler || gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: jsize
        run: |
          cd ./db
          bundle exec jsize.sh

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet && git diff --staged --quiet || git commit -m "Convert data.json to data.js" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  js-check:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Typescript check
        run: yarn -s tsc

      - name: Jest tests
        run: yarn test

  deploy:
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-args: "--prod"
