on:
  push:
    branches:
      - "**"
      - "!master"
    paths:
      - "**.tsx"
      - "**.ts"
      - "**.js"
      - "**.json"
      - "**.yml"

jobs:
  test:
    # Cypress seem to have problems with ubuntu-latest
    runs-on: ubuntu-16.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - run: yarn lint
      - run: yarn test --coverage

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn now dev --listen 1986

      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage/clover.xml

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: amondnet/now-deployment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID }}
          now-org-id: ${{ secrets.ZEIT_ORG_ID }}
          now-args: "--confirm"
          github-comment: true
