on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - run: yarn lint
      - run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1

      - uses: amondnet/now-deployment@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-project-id: ${{ secrets.ZEIT_PROJECT_ID }}
          now-org-id: ${{ secrets.ZEIT_ORG_ID }}
          now-args: "--confirm --prod"
